//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance_record
    {
        public long Id { get; set; }
        public string Barcode { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string LocationId { get; set; }
        public string TimeslotId { get; set; }
    
        public virtual attendance_location attendance_location { get; set; }
        public virtual attendance_timeslot attendance_timeslot { get; set; }
    }
}
