//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class offered
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public offered()
        {
            this.enrollments = new HashSet<enrollment>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<bool> DE { get; set; }
        public Nullable<int> Enrolled { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string CourseNumber { get; set; }
        public Nullable<int> FacultyId { get; set; }
    
        public virtual cours cours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enrollment> enrollments { get; set; }
        public virtual faculty faculty { get; set; }
    }
}
